/* crear un procedimiento que dado un valor x, muestre
el numero de empleados que ganen mas que ese valor */

CREATE OR REPLACE PROCEDURE SP_FILTRO_SUELDO (P_SUELDO_CORTE IN NUMBER, P_CANTIDAD_EMP OUT NUMBER)
AS
BEGIN
    P_CANTIDAD_EMP := 0;
    FOR REG_EMP IN 
    (SELECT
            69
        FROM EMPLOYEES
        WHERE SALARY > P_SUELDO_CORTE) LOOP
        
        P_CANTIDAD_EMP := P_CANTIDAD_EMP + 1;
    END LOOP;
    
    -- P_CANTIDAD_EMP := SQL%ROWCOUNT;
END;

DECLARE
    V_SUELDO NUMBER := &V_SUELDO;
    V_CANTIDAD NUMBER;
BEGIN
    SP_FILTRO_SUELDO(V_SUELDO, V_CANTIDAD);
    
    DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE TRABAJADORES QUE GANAN MÁS QUE '||V_SUELDO||' ES '||V_CANTIDAD);
END;


CREATE TABLE EMPLEADITO(ID NUMBER(10), NOMBRE VARCHAR2(500), SUELDO NUMBER(20));

CREATE OR REPLACE PROCEDURE SP_GRABA_EMP (P_ID NUMBER, P_NOMBRE VARCHAR2, P_SUELDO NUMBER)
AS
BEGIN
    INSERT INTO EMPLEADITO VALUES(P_ID, P_NOMBRE, P_SUELDO);
END;

CREATE OR REPLACE PROCEDURE SP_PRINCIPAL(P_JOB VARCHAR2)
AS
BEGIN
    FOR REG_EMP IN
    (SELECT
        employee_id,
        first_name,
        salary
    FROM EMPLOYEES
    WHERE JOB_ID = P_JOB) LOOP
    
        SP_GRABA_EMP(REG_EMP.employee_id, REG_EMP.first_name, REG_EMP.salary);
    
    END LOOP;
END;

EXEC SP_PRINCIPAL('SH_CLERK');