CREATE OR REPLACE PACKAGE PKG_PROC_REMUN
IS
    V_MENSAJE_ERROR VARCHAR2(200);
    V_RUTINA_ERROR VARCHAR2(200);
    V_SEC_ERROR NUMBER:=0;
    
    CURSOR CUR_EMP_TRABAJA IS
        SELECT
            E.employee_id,
            COUNT(M.employee_id) TOTAL_EMP,
            E.SALARY SALARIO,
            ROUND(E.SALARY*NVL(E.COMMISSION_PCT, 0)) TOTAL_COMISION,
            L.CITY
        FROM EMPLOYEES E
        LEFT JOIN EMPLOYEES M
        ON E.employee_id = M.employee_id
        LEFT JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        LEFT JOIN LOCATIONS L
        ON L.LOCATION_ID = D.LOCATION_ID
        GROUP BY E.EMPLOYEE_ID, E.SALARY, E.COMMISSION_PCT, L.CITY;
        
        FUNCTION F_OBT_DESCT_SINDICATO(P_SUELDO_BASE NUMBER, P_ID_EMP NUMBER) RETURN NUMBER;
        
        PROCEDURE P_GRABAR_ERROR(P_RUTINA_ERROR VARCHAR2, P_MENSAJE_ERROR VARCHAR2);
END PKG_PROC_REMUN;

CREATE OR REPLACE PACKAGE BODY PKG_PROC_REMUN
IS
    FUNCTION F_OBT_DESCT_SINDICATO(P_SUELDO_BASE NUMBER, P_ID_EMP NUMBER)
    RETURN NUMBER
    IS
        V_DESCT_SINDICATO NUMBER;
    BEGIN
        SELECT
            ROUND(P_SUELDO_BASE*TDS.PORC_DS)
        INTO V_DESCT_SINDICATO
        FROM TRAMO_DESCTO_SINDICATO TDS
        WHERE P_SUELDO_BASE BETWEEN TDS.TRAMO_INF_DS AND TDS.TRAMO_SUP_DS;
        
        RETURN V_DESCT_SINDICATO;
        
    EXCEPTION
        WHEN OTHERS THEN
            V_MENSAJE_ERROR := SQLERRM;
            V_RUTINA_ERROR := 'ERROR EN F_OBT_DESCT_SINDICATO, EMP: '||P_ID_EMP;
            RETURN -1;
    END F_OBT_DESCT_SINDICATO;
    
    PROCEDURE P_GRABAR_ERROR(P_RUTINA_ERROR VARCHAR2, P_MENSAJE_ERROR VARCHAR2)
    IS
    BEGIN
        V_SEC_ERROR := V_SEC_ERROR + 1;
        INSERT INTO ERROR_PROCESO VALUES(V_SEC_ERROR, P_RUTINA_ERROR, P_MENSAJE_ERROR);
    END P_GRABAR_ERROR;
END PKG_PROC_REMUN;

SELECT
    EMPLOYEE_ID,
    SALARY,
    PKG_PROC_REMUN.f_obt_desct_sindicato(SALARY, EMPLOYEE_ID) DESCT_SINDICATO
FROM EMPLOYEES;