DECLARE
   /* TYPE VARRAY_EJEMPLO_TIPO IS VARRAY (LIMITE_SUPERIOR)
    OF TIPO_ELEMENTO*/
    TYPE VARRAY_EJEMPLO_TIPO IS VARRAY(4) OF NUMBER; --CREAMOS EL TIPO DE VARRAY
    VARRAY_EJEMPLO VARRAY_EJEMPLO_TIPO;  
    ID NUMBER;
    RESULTADO NUMBER;
BEGIN
    ID:=5;
    VARRAY_EJEMPLO:=VARRAY_EJEMPLO_TIPO(30,5);
    DBMS_OUTPUT.PUT_LINE(VARRAY_EJEMPLO(2));
    VARRAY_EJEMPLO(2):=22;
    DBMS_OUTPUT.PUT_LINE(VARRAY_EJEMPLO(2));
    --EXTEND --> HABILITA UN NUEVO ESPACIO EN EL VARRAY
    VARRAY_EJEMPLO.EXTEND(2);
    VARRAY_EJEMPLO(3):=7;
    VARRAY_EJEMPLO(4):=55;
    RESULTADO:=500000*(VARRAY_EJEMPLO(1)/100);
    DBMS_OUTPUT.PUT_LINE(RESULTADO);
END;


-----------------------------------------------------------
-----------------------------------------------------------

/*
SE SOLICITA CREAR UN PROGRAMA QUE CONTENGA
EL ID, NOMBRE, DEPARTAMENTO Y CIUDAD, SUELDO
Y SUELDO+BONO
DE LOS TRABAJADORES DE LA EMPRESA.
ADEMAS, DEBE CREAR UN VARRAY QUE 
CONTENGA LOS % DE BONIFICACION SEGÚN 
CIUDAD.
PARA QUIENES TRABAJEN EN Oxford,
EL BONO ES DEL 15%
Seattle ES DEL 20%
Singapore ES EL 25%.
*/
/
SELECT
    e.employee_id,
    e.first_name||' '||e.last_name NOMBRE,
    d.department_name, 
    L.CITY,
    E.SALARY
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
JOIN LOCATIONS L 
ON d.location_id = l.location_id;
-------------------------------------
/
DECLARE
    TYPE TIPO_VARRAY_PORC IS VARRAY (3) OF NUMBER;
    VARRAY_PORC TIPO_VARRAY_PORC;
    
    CURSOR CUR_EMPLEADOS IS 
        SELECT
            e.employee_id,
            e.first_name||' '||e.last_name NOMBRE,
            d.department_name, 
            L.CITY,
            E.SALARY
        FROM EMPLOYEES E JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
        JOIN LOCATIONS L 
        ON d.location_id = l.location_id;
        
        TYPE REGISTRO_TIPO IS RECORD (
        ID NUMBER,
        NOMBRE VARCHAR2(50),
        DEPARTAMENTO VARCHAR2(30),
        CIUDAD VARCHAR2(50),
        SALARY NUMBER
        );
        REGISTRO REGISTRO_TIPO;
        V_MIN NUMBER;
        V_MAX NUMBER;
        BONO NUMBER;
BEGIN
    
    VARRAY_PORC:=TIPO_VARRAY_PORC(15,20,25);
    SELECT MIN(EMPLOYEE_ID),MAX(EMPLOYEE_ID)
    INTO V_MIN,V_MAX
    FROM EMPLOYEES;  
    OPEN CUR_EMPLEADOS;
    LOOP
        BONO:=0;
        FETCH CUR_EMPLEADOS INTO REGISTRO;
        IF REGISTRO.CIUDAD='Oxford' THEN
            BONO:=REGISTRO.SALARY*(VARRAY_PORC(1)/100);
        ELSIF REGISTRO.CIUDAD='Seattle' THEN
            BONO:=REGISTRO.SALARY*(VARRAY_PORC(2)/100);
        ELSIF REGISTRO.CIUDAD='Singapore' THEN
            BONO:=REGISTRO.SALARY*(VARRAY_PORC(3)/100);
        END IF;
        
        DBMS_OUTPUT.PUT_LINE(' D A T O S   T R A B A J A D O R');
        DBMS_OUTPUT.PUT_LINE('ID           : '||REGISTRO.ID);
        DBMS_OUTPUT.PUT_LINE('NOMBRE       : '||REGISTRO.NOMBRE);
        DBMS_OUTPUT.PUT_LINE('DEPARTAMENTO : '||REGISTRO.DEPARTAMENTO);
        DBMS_OUTPUT.PUT_LINE('CIUDAD       : '||REGISTRO.CIUDAD);
        DBMS_OUTPUT.PUT_LINE('SUELDO       : '||REGISTRO.SALARY);
        DBMS_OUTPUT.PUT_LINE('BONO         : '||BONO);
        EXIT WHEN V_MIN>V_MAX;
        V_MIN:=V_MIN+1;
    END LOOP;
END;
