SET SERVEROUTPUT ON;

DECLARE
    CURSOR CUR_EMPLEADOS (P_DPTO_ID NUMBER, P_MIN_SALARY NUMBER) IS
        SELECT 
            *
        FROM EMPLOYEES
        WHERE DEPARTMENT_ID = P_DPTO_ID AND SALARY >= P_MIN_SALARY;
        
        V_DPTO NUMBER;
        V_MINSALARY NUMBER;
BEGIN
    V_DPTO := 150;
    V_MINSALARY := 2700;
    
    DBMS_OUTPUT.PUT_LINE('MOSTRANDO LOS EMPLEADOS DEL DEPARTAMENTO ID: '||V_DPTO||' CON SALARIO MINIMO: '||V_MINSALARY);
    
    FOR REGISTRO IN CUR_EMPLEADOS (V_DPTO, V_MINSALARY) LOOP
        DBMS_OUTPUT.PUT_LINE('ID     : '||REGISTRO.EMPLOYEE_ID);
        DBMS_OUTPUT.PUT_LINE('NOMBRE : '||REGISTRO.FIRST_NAME||' '||REGISTRO.LAST_NAME);
        DBMS_OUTPUT.PUT_LINE('SUELDO : '||REGISTRO.SALARY);
        DBMS_OUTPUT.PUT_LINE('DPTO   : '||REGISTRO.DEPARTMENT_ID);
        DBMS_OUTPUT.PUT_LINE('-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-');
    END LOOP;
END;