--- FUNCIONES ALMACENADAS----
CREATE OR REPLACE  FUNCTION FN_NOMBRE
[PARAMETROS TIPODATO....] RETURN TIPODATO AS|IS
    VARIABLES TIPODATOVARIABLE
    ....
BEGIN

    RETURN
EXCEPTION

    RETURN
END;
------
--------------------------
/
----
/*
CREAR UNA FUNCION QUE RETORNE LA CANTIDAD DE AÑOS
QUE LLEVA TRABAJANDO UN EMPLEADO.
*/

CREATE OR REPLACE FUNCTION FN_ANIOS_TRAB 
(P_ID NUMBER) RETURN NUMBER 
IS
    V_ANIOS NUMBER;
BEGIN
    SELECT TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12)
    INTO V_ANIOS
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID=P_ID;
    RETURN V_ANIOS;
END;

SELECT
FIRST_NAME||' '||LAST_NAME NOMBRE,
FN_ANIOS_TRAB(EMPLOYEE_ID) ANTIGUEDAD
FROM EMPLOYEES;

--------
CREAR UNA FUNCION QUE RETORNE EL MONTO DE LA COMISION 
DE UN TRABAJADOR. SI EL TRABAJADOR NO TIENE ESE VALOR
DEBE RETORNAR 0 (NO PUEDE USAR NVL)
-----------
CREATE TABLE BONO (
INICIAL NUMBER,
FINAL NUMBER,
MONTO NUMBER);

INSERT INTO BONO VALUES (1,10,10);
INSERT INTO BONO VALUES (11,20,15);
INSERT INTO BONO VALUES (21,30,20);

---
CREATE OR REPLACE FUNCTION FN_BONO (
    P_ID_EMP NUMBER,
    P_SALARIO NUMBER,
    P_ANIOS NUMBER)
RETURN NUMBER IS
    V_BONO NUMBER;
BEGIN
    SELECT
        MONTO*P_SALARIO 
        INTO V_BONO
    FROM BONO 
    WHERE P_ANIOS BETWEEN INICIAL AND FINAL;
    RETURN V_BONO;
END;
--------
SELECT 
    EMPLOYEE_ID,
    SALARY,
    FN_BONO(EMPLOYEE_ID,SALARY,FN_ANIOS_TRAB(EMPLOYEE_ID)) BONO
FROM EMPLOYEES
WHERE EMPLOYEE_ID=100;





