SET SERVEROUTPUT ON;

CREATE SEQUENCE SEQ_ERROR_PROCESO;

DECLARE
    V_MENSAJE_ERROR VARCHAR2(250);
    V_CODIGO_ERROR NUMBER;
    
    V_DPTO NUMBER;
    
    ERROR_DPTO EXCEPTION;
BEGIN

    V_DPTO := 300;
    
    IF V_DPTO>=300 THEN
        RAISE ERROR_DPTO;
    ELSE
        INSERT INTO DEPARTMENTS VALUES(V_DPTO, 'HOLA', 200, 1700);
    END IF;
EXCEPTION
    WHEN ERROR_DPTO THEN
        INSERT INTO ERROR_PROCESO VALUES(SEQ_ERROR_PROCESO.NEXTVAL, 'EL DEPA NO PUEDE SER MAYOR A 300', 'WEA');
END;

--

DECLARE 
    NOMBRE_EXCEPTION EXCEPTION;
BEGIN
    IF CONDICION THEN
        RAISE NOMBRE_EXCEPTION;

EXCPETION
    WHEN NOMBRE_EXCEPTION THEN
        HOLA MUNDO;
END;

--

