create sequence SEQ_RESUL_PROC;

DECLARE
    CURSOR CUR_JEFE_EMP IS
            SELECT E.EMPLOYEE_ID ,
            COUNT(M.EMPLOYEE_ID) TOTAL_EMP
        FROM EMPLOYEES E JOIN EMPLOYEES M
        ON E.EMPLOYEE_ID=M.MANAGER_ID
        GROUP BY E.EMPLOYEE_ID
        ORDER BY E.EMPLOYEE_ID;
    V_PORC_ASIG_JEFE NUMBER;
    V_EMP_PRO NUMBER;
    V_TOTAL_ACT NUMBER;
    V_ERRORES NUMBER;
    
    V_MENSAJE_ERROR VARCHAR2(250);
    V_CODIGO_ERROR NUMBER;
BEGIN
    V_ERRORES:=0;
    FOR REG_JEFE_EMP IN CUR_JEFE_EMP LOOP
        V_EMP_PRO:=V_EMP_PRO+1;
        IF REG_JEFE_EMP.TOTAL_EMP>0 THEN
            -- INICIO BLOQUE ANIDADO
            BEGIN
                SELECT AJ.PORC_ASIG_JEFE
                    INTO V_PORC_ASIG_JEFE
                FROM TRAMO_ASIG_JEFE AJ
                WHERE REG_JEFE_EMP.TOTAL_EMP BETWEEN AJ.TRAMO_INF_AJ AND
                AJ.TRAMO_SUP_AJ;
            -- EXCEPTION BLOQUE ANIDADO
             EXCEPTION
                WHEN others THEN 
                    V_MENSAJE_ERROR := SQLERRM;
                    V_CODIGO_ERROR := SQLCODE;
                    V_PORC_ASIG_JEFE:=0;
                    V_ERRORES:=V_ERRORES+1;
                    INSERT INTO RESULTADO_PROCESO VALUES (SEQ_RESUL_PROC.NEXTVAL,
                    'PROCESO DE BONOS',v_mensaje_error||' - '||v_codigo_error);
            END; -- FIN BLOQUE ANIDADO
        END IF;
    UPDATE EMPLEADOS
        SET SALARY=SALARY+ROUND(SALARY*NVL(COMMISSION_PCT,0))+
        ROUND(SALARY*(V_PORC_ASIG_JEFE/100))
        WHERE EMPLOYEe_ID=REG_JEFE_EMP.EMPLOYEE_ID;
        V_TOTAL_ACT:=V_TOTAL_ACT+1;
    END LOOP;
    INSERT INTO RESULTADO_PROCESO VALUES (SEQ_RESUL_PROC.NEXTVAL,
    'PROCESO DE BONOS','ERRORES : '||V_ERRORES||' - '||v_mensaje_error||' - '||v_codigo_error);
EXCEPTION
    WHEN others THEN 
        V_PORC_ASIG_JEFE:=0;
END;