-- Quiero llenar una tabla de cálculo de promedios digamos TABLA(ALUMNO, FACULTAD, CARRERA, ASIGNATURA, PROMEDIOS (Y NOTAS TALVEZ), SITUACION)
-- EN CASO DE ERROR LLENAR UNA TABLA PROC_ERROR(EN QUE PROCESO DA ERROR, ERROR, Y SU CODIGO)
CREATE OR REPLACE PACKAGE PKG_PROC_CALC_PROMEDIO
IS
    V_MENSAJE_ERROR VARCHAR2(200);
    V_RUTINA_ERROR VARCHAR2(200);
    V_SEC_ERROR NUMBER:=0;
	
	-- ¿Qué debería obtener de aqui para que resulte?
	-- OBTENER AL ALUMNO SU CARRERA, ASIGNATURAS Y SUS NOTAS DE ELLAS
	-- LUEGO GUARDO LAS NOTAS EN UN VARRAY Y LOS METO A LA FUNC F_OBT_PROM_ALUM Y DEJO FILTRADO POR ASIGNATURA
	CURSOR CUR_ALUM_PROC_CALC_PROMEDIO IS
		SELECT
			e.id_estudiante,
			-- (funcion para retornar el nombre completo a travez de la id),
			e.run || '-' || e.dv,
			c.nombre_carrera
			a.nombre_asignatura,
			ev.tipo_evaluacion,
			rev.nota_resul_eval
		FROM ESTUDIANTE e
		JOIN CARRERA c
		ON e.id_carrera = c.id_carrera
		JOIN INSCRIPCION i
		ON e.id_estudiante = i.id_estudiante
		JOIN ASIGNATURA a
		ON i.id_asignatura = a.id_asignatura
		JOIN EVALUACION ev
		ON ev.id_asignatura = a.id_asignatura
		JOIN RESULTADO_EVALUACION rev
		ON rev.id_evaluacion = ev.id_evaluacion
			
			
	FUNCTION F_OBT_PROM_ALUM(P_ID_ALUMNO NUMBER) RETURN NUMBER; -- DEVUELVE EL PROMEDIO DE LAS ASIGNATURAS QUE TIENE INSCRITAS EN EL SEMESTRE
	FUNCTION F_OBT_SITUACION_ALUMN(P_ID_ALUMN NUMBER, P_PROMEDIO NUMBER) RETURN VARCHAR2; -- DEVUELVE LA SITUACIÓN DE EL ESTUDIANTE EN LA ASIGNATURA¿DEBERIA SER 1 Y LLAMARLA DENTRO DE UN BUCLE?
	
	PROCEDURE P_GRABAR_ERROR(P_RUTINA_ERROR VARCHAR2, P_MENSAJE_ERROR VARCHAR2);
	PROCEDURE P_GRABAR_CALC_PROM_ALUMNO(--NOSE AUN);
	
END PKG_PROC_CALC_PROMEDIO;

CREATE OR REPLACE PACKAGE BODY PKG_PROC_CALC_PROMEDIO
IS
END PKG_PROC_CALC_PROMEDIO;