SET SERVEROUTPUT ON; -- activa la salida dbms

DECLARE
    /*
    CREAMOS UN TIPO DE DATO PARA EL REGISTRO_EMPLEADO
    CREAMOS LAS COLUMNAS DEL REGISTRO
    */
    /*TYPE TIPO_REGISTRO_EMPLEADO IS RECORD(
    ID NUMBER,
    NOMBRE VARCHAR2(30),
    SUELDO NUMBER);*/
    
    -- REGISTRO_EMPLEADO TIPO_REGISTRO_EMPLEADO; -- CREAMOS UNA VARIABLE DE TIPO REGISTRO_EMPLEADO
    
    REGISTRO_EMPLEADO EMPLOYEES%ROWTYPE;
    
    -- DEFINIMOS DOS VARIABLES PARA VER LOS LIMITES DEL CONJUNTO DE LA TABLA EMPLOYEES
    V_MIN NUMBER; 
    V_MAX NUMBER;
BEGIN
    SELECT MIN(EMPLOYEE_ID), MAX(EMPLOYEE_ID)
        INTO V_MIN, V_MAX
    FROM EMPLOYEES; -- SUB CONSULTA PARA LLENAR CON LAS ID MINIMAS Y MAXIMAS DE LA TABLA EMPLOYEES
    
    LOOP -- ABRIMOS EL LOOP
        /*SELECT EMPLOYEE_ID,
            FIRST_NAME||' '||LAST_NAME,
            SALARY
            INTO REGISTRO_EMPLEADO
        FROM EMPLOYEES
        WHERE EMPLOYEE_ID = V_MIN; CREAMOS UN SELECT PARA LLENAR EL REGISTRO JUSTO EN LA ID ITERADA*/
        
        SELECT 
            *
            INTO REGISTRO_EMPLEADO
        FROM EMPLOYEES
        WHERE EMPLOYEE_ID = V_MIN;
        
        -- si lo hacemos de la manera con * se copia exactamente la tabla en este caso employees
        DBMS_OUTPUT.PUT_LINE('ID: '||REGISTRO_EMPLEADO.employee_id||' NOMBRE: '|| REGISTRO_EMPLEADO.first_name||' SUELDO: '||REGISTRO_EMPLEADO.salary);
        
        EXIT WHEN V_MIN >= V_MAX; -- CLAUSULA DE SALIDA DEL BUCLE LOOP
        V_MIN := V_MIN + 1; -- AUMENTAMOS EL ID ITERADO
    END LOOP; -- SALIMOS DEL LOOP
END;