CREATE TABLE ESTUDIANTES(
	id_estudiante NUMBER PRIMARY KEY,
	pnombre VARCHAR2(50) NOT NULL,
	snombre VARCHAR2(50),
	papellido VARCHAR2(50) NOT NULL,
	sapellido VARCHAR2(50)
	run NUMBER NOT NULL,
	dv VARCHAR2(1) NOT NULL,
	año_ingreso NUMBER(4) NOT NULL,
	FOREIGN KEY (id_carrera) REFERENCES CARRERAS(id_carrera));
	
CREATE TABLE DOCENTES(
	id_docente NUMBER PRIMARY KEY,
	pnombre VARCHAR2(50) NOT NULL,
	snombre VARCHAR2(50),
	papellido VARCHAR2(50) NOT NULL,
	sapellido VARCHAR2(50),
	run NUMBER NOT NULL,
	dv VARCHAR2(1) NOT NULL,
	FOREIGN KEY (id_especialidad) REFERENCES ESPECIALIDAD(id_especialidad));
	
CREATE TABLE CARRERAS(
	id_carrera NUMBER PRIMARY KEY,
	codigo VARCHAR2(50) NOT NULL,
	nombre VARCHAR2(50) NOT NULL,
	FOREIGN KEY (id_facultad) REFERENCES FACULTAD(id_facultad));
	
CREATE TABLE ASIGNATURA(
	id_asignatura NUMBER PRIMARY KEY,
	codigo VARCHAR2(50) NOT NULL,
	nombre VARCHAR2(50) NOT NULL,
	creditos NUMBER NOT NULL,
	nivel NUMBER NOT NULL,
	FOREIGN KEY (id_carrera) REFERENCES CARRERAS(id_carrera));
	
CREATE TABLE SEMESTRES(
	id_semestre NUMBER PRIMARY KEY,
	año NUMBER(4) NOT NULL, -- AÑO TIPO 2025, 2026, 2027
	periodo VARCHAR2(50) NOT NULL,
	fecha_ini DATE, -- USARIA TIMESTAMP PERO NI SI QUIERA NECESITO LA HORA
	fecha_ter DATE);
	
CREATE TABLE INSCRIPCIONES(
	id_inscripcion NUMBER PRIMARY KEY,
	FOREIGN KEY (id_estudiante) REFERENCES ESTUDIANTES(id_estudiante),
	FOREIGN KEY (id_asignatura) REFERENCES ASIGNATURA(id_asignatura),
	FOREIGN KEY (id_docente) REFERENCES DOCENTES(id_docente),
	FOREIGN KEY (id_semestre) REFERENCES SEMESTRES(id_semestre),
	nota_final NUMBER);
	
CREATE TABLE EVALUACIONES(
	id_evaluacion NUMBER PRIMARY KEY,
	codigo VARCHAR2(50) NOT NULL,
	tipo VARCHAR2(50) NOT NULL,
	fecha DATE NOT NULL,
	puntaje_maximo NUMBER,
	FOREIGN KEY (id_asignatura) REFERENCES ASIGNATURA(id_asignatura));
	
CREATE TABLE RESULTADO_EVALUACIONES(
	id_resul_eval NUMBER PRIMARY KEY,
	FOREIGN KEY (id_estudiante) REFERENCES ESTUDIANTES(id_estudiante),
	FOREIGN KEY (id_evaluacion) REFERENCES EVALUACIONES(id_evaluacion),
	puntaje_obt NUMBER);
	
CREATE TABLE ESPECIALIDAD(
	id_especialidad NUMBER PRIMARY KEY,
	nombre VARCHAR2(50) NOT NULL);
	
CREATE TABLE FACULTAD(
	id_facultad NUMBER PRIMARY KEY,
	nombre VARCHAR2(50) NOT NULL);